/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Athlete {
  'id' : AthleteId,
  'bio' : string,
  'name' : string,
  'sport' : string,
  'achievements' : Array<string>,
  'position' : string,
}
export type AthleteId = bigint;
export type EventId = bigint;
export interface NewsHighlight {
  'id' : NewsId,
  'title' : string,
  'date' : Time,
  'summary' : string,
  'category' : string,
}
export type NewsId = bigint;
export type SportId = bigint;
export interface SportsCategory {
  'id' : SportId,
  'name' : string,
  'description' : string,
  'iconLabel' : string,
}
export interface SportsEvent {
  'id' : EventId,
  'status' : Status,
  'title' : string,
  'date' : Time,
  'description' : string,
  'sportType' : string,
  'location' : string,
}
export type Status = { 'upcoming' : null } |
  { 'live' : null } |
  { 'completed' : null };
export type Time = bigint;
export interface _SERVICE {
  'createAthlete' : ActorMethod<
    [string, string, string, string, Array<string>],
    AthleteId
  >,
  'createEvent' : ActorMethod<
    [string, string, Time, string, string, Status],
    EventId
  >,
  'createNews' : ActorMethod<[string, string, string, Time], NewsId>,
  'createSportsCategory' : ActorMethod<[string, string, string], SportId>,
  'deleteAthlete' : ActorMethod<[AthleteId], undefined>,
  'deleteEvent' : ActorMethod<[EventId], undefined>,
  'deleteNews' : ActorMethod<[NewsId], undefined>,
  'deleteSportsCategory' : ActorMethod<[SportId], undefined>,
  'getAllAthletes' : ActorMethod<[], Array<Athlete>>,
  'getAllData' : ActorMethod<
    [],
    {
      'news' : Array<NewsHighlight>,
      'athletes' : Array<Athlete>,
      'events' : Array<SportsEvent>,
      'sportsCategories' : Array<SportsCategory>,
    }
  >,
  'getAllEvents' : ActorMethod<[], Array<SportsEvent>>,
  'getAllNews' : ActorMethod<[], Array<NewsHighlight>>,
  'getAllSportsCategories' : ActorMethod<[], Array<SportsCategory>>,
  'getEventsByStatus' : ActorMethod<[Status], Array<SportsEvent>>,
  'updateAthlete' : ActorMethod<
    [AthleteId, string, string, string, string, Array<string>],
    undefined
  >,
  'updateEvent' : ActorMethod<
    [EventId, string, string, Time, string, string, Status],
    undefined
  >,
  'updateNews' : ActorMethod<[NewsId, string, string, string, Time], undefined>,
  'updateSportsCategory' : ActorMethod<
    [SportId, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];