/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AthleteId = IDL.Nat;
export const Time = IDL.Int;
export const Status = IDL.Variant({
  'upcoming' : IDL.Null,
  'live' : IDL.Null,
  'completed' : IDL.Null,
});
export const EventId = IDL.Nat;
export const NewsId = IDL.Nat;
export const SportId = IDL.Nat;
export const Athlete = IDL.Record({
  'id' : AthleteId,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'sport' : IDL.Text,
  'achievements' : IDL.Vec(IDL.Text),
  'position' : IDL.Text,
});
export const NewsHighlight = IDL.Record({
  'id' : NewsId,
  'title' : IDL.Text,
  'date' : Time,
  'summary' : IDL.Text,
  'category' : IDL.Text,
});
export const SportsEvent = IDL.Record({
  'id' : EventId,
  'status' : Status,
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'sportType' : IDL.Text,
  'location' : IDL.Text,
});
export const SportsCategory = IDL.Record({
  'id' : SportId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'iconLabel' : IDL.Text,
});

export const idlService = IDL.Service({
  'createAthlete' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [AthleteId],
      [],
    ),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text, Status],
      [EventId],
      [],
    ),
  'createNews' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Time], [NewsId], []),
  'createSportsCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [SportId],
      [],
    ),
  'deleteAthlete' : IDL.Func([AthleteId], [], []),
  'deleteEvent' : IDL.Func([EventId], [], []),
  'deleteNews' : IDL.Func([NewsId], [], []),
  'deleteSportsCategory' : IDL.Func([SportId], [], []),
  'getAllAthletes' : IDL.Func([], [IDL.Vec(Athlete)], ['query']),
  'getAllData' : IDL.Func(
      [],
      [
        IDL.Record({
          'news' : IDL.Vec(NewsHighlight),
          'athletes' : IDL.Vec(Athlete),
          'events' : IDL.Vec(SportsEvent),
          'sportsCategories' : IDL.Vec(SportsCategory),
        }),
      ],
      ['query'],
    ),
  'getAllEvents' : IDL.Func([], [IDL.Vec(SportsEvent)], ['query']),
  'getAllNews' : IDL.Func([], [IDL.Vec(NewsHighlight)], ['query']),
  'getAllSportsCategories' : IDL.Func([], [IDL.Vec(SportsCategory)], ['query']),
  'getEventsByStatus' : IDL.Func([Status], [IDL.Vec(SportsEvent)], ['query']),
  'updateAthlete' : IDL.Func(
      [AthleteId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateEvent' : IDL.Func(
      [EventId, IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text, Status],
      [],
      [],
    ),
  'updateNews' : IDL.Func([NewsId, IDL.Text, IDL.Text, IDL.Text, Time], [], []),
  'updateSportsCategory' : IDL.Func(
      [SportId, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AthleteId = IDL.Nat;
  const Time = IDL.Int;
  const Status = IDL.Variant({
    'upcoming' : IDL.Null,
    'live' : IDL.Null,
    'completed' : IDL.Null,
  });
  const EventId = IDL.Nat;
  const NewsId = IDL.Nat;
  const SportId = IDL.Nat;
  const Athlete = IDL.Record({
    'id' : AthleteId,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'sport' : IDL.Text,
    'achievements' : IDL.Vec(IDL.Text),
    'position' : IDL.Text,
  });
  const NewsHighlight = IDL.Record({
    'id' : NewsId,
    'title' : IDL.Text,
    'date' : Time,
    'summary' : IDL.Text,
    'category' : IDL.Text,
  });
  const SportsEvent = IDL.Record({
    'id' : EventId,
    'status' : Status,
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'sportType' : IDL.Text,
    'location' : IDL.Text,
  });
  const SportsCategory = IDL.Record({
    'id' : SportId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'iconLabel' : IDL.Text,
  });
  
  return IDL.Service({
    'createAthlete' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [AthleteId],
        [],
      ),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text, Status],
        [EventId],
        [],
      ),
    'createNews' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Time], [NewsId], []),
    'createSportsCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [SportId],
        [],
      ),
    'deleteAthlete' : IDL.Func([AthleteId], [], []),
    'deleteEvent' : IDL.Func([EventId], [], []),
    'deleteNews' : IDL.Func([NewsId], [], []),
    'deleteSportsCategory' : IDL.Func([SportId], [], []),
    'getAllAthletes' : IDL.Func([], [IDL.Vec(Athlete)], ['query']),
    'getAllData' : IDL.Func(
        [],
        [
          IDL.Record({
            'news' : IDL.Vec(NewsHighlight),
            'athletes' : IDL.Vec(Athlete),
            'events' : IDL.Vec(SportsEvent),
            'sportsCategories' : IDL.Vec(SportsCategory),
          }),
        ],
        ['query'],
      ),
    'getAllEvents' : IDL.Func([], [IDL.Vec(SportsEvent)], ['query']),
    'getAllNews' : IDL.Func([], [IDL.Vec(NewsHighlight)], ['query']),
    'getAllSportsCategories' : IDL.Func(
        [],
        [IDL.Vec(SportsCategory)],
        ['query'],
      ),
    'getEventsByStatus' : IDL.Func([Status], [IDL.Vec(SportsEvent)], ['query']),
    'updateAthlete' : IDL.Func(
        [AthleteId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateEvent' : IDL.Func(
        [EventId, IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text, Status],
        [],
        [],
      ),
    'updateNews' : IDL.Func(
        [NewsId, IDL.Text, IDL.Text, IDL.Text, Time],
        [],
        [],
      ),
    'updateSportsCategory' : IDL.Func(
        [SportId, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };