/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SportsCategory {
    id: SportId;
    name: string;
    description: string;
    iconLabel: string;
}
export type Time = bigint;
export type SportId = bigint;
export type NewsId = bigint;
export interface NewsHighlight {
    id: NewsId;
    title: string;
    date: Time;
    summary: string;
    category: string;
}
export type EventId = bigint;
export interface SportsEvent {
    id: EventId;
    status: Status;
    title: string;
    date: Time;
    description: string;
    sportType: string;
    location: string;
}
export interface Athlete {
    id: AthleteId;
    bio: string;
    name: string;
    sport: string;
    achievements: Array<string>;
    position: string;
}
export type AthleteId = bigint;
export enum Status {
    upcoming = "upcoming",
    live = "live",
    completed = "completed"
}
export interface backendInterface {
    createAthlete(name: string, sport: string, position: string, bio: string, achievements: Array<string>): Promise<AthleteId>;
    createEvent(title: string, sportType: string, date: Time, location: string, description: string, status: Status): Promise<EventId>;
    createNews(title: string, summary: string, category: string, date: Time): Promise<NewsId>;
    createSportsCategory(name: string, description: string, iconLabel: string): Promise<SportId>;
    deleteAthlete(athleteId: AthleteId): Promise<void>;
    deleteEvent(eventId: EventId): Promise<void>;
    deleteNews(newsId: NewsId): Promise<void>;
    deleteSportsCategory(categoryId: SportId): Promise<void>;
    getAllAthletes(): Promise<Array<Athlete>>;
    getAllData(): Promise<{
        news: Array<NewsHighlight>;
        athletes: Array<Athlete>;
        events: Array<SportsEvent>;
        sportsCategories: Array<SportsCategory>;
    }>;
    getAllEvents(): Promise<Array<SportsEvent>>;
    getAllNews(): Promise<Array<NewsHighlight>>;
    getAllSportsCategories(): Promise<Array<SportsCategory>>;
    getEventsByStatus(status: Status): Promise<Array<SportsEvent>>;
    updateAthlete(athleteId: AthleteId, name: string, sport: string, position: string, bio: string, achievements: Array<string>): Promise<void>;
    updateEvent(eventId: EventId, title: string, sportType: string, date: Time, location: string, description: string, status: Status): Promise<void>;
    updateNews(newsId: NewsId, title: string, summary: string, category: string, date: Time): Promise<void>;
    updateSportsCategory(categoryId: SportId, name: string, description: string, iconLabel: string): Promise<void>;
}
import type { Athlete as _Athlete, EventId as _EventId, NewsHighlight as _NewsHighlight, SportsCategory as _SportsCategory, SportsEvent as _SportsEvent, Status as _Status, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createAthlete(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>): Promise<AthleteId> {
        if (this.processError) {
            try {
                const result = await this.actor.createAthlete(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAthlete(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createEvent(arg0: string, arg1: string, arg2: Time, arg3: string, arg4: string, arg5: Status): Promise<EventId> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0, arg1, arg2, arg3, arg4, to_candid_Status_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0, arg1, arg2, arg3, arg4, to_candid_Status_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createNews(arg0: string, arg1: string, arg2: string, arg3: Time): Promise<NewsId> {
        if (this.processError) {
            try {
                const result = await this.actor.createNews(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNews(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createSportsCategory(arg0: string, arg1: string, arg2: string): Promise<SportId> {
        if (this.processError) {
            try {
                const result = await this.actor.createSportsCategory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSportsCategory(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteAthlete(arg0: AthleteId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAthlete(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAthlete(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: EventId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteNews(arg0: NewsId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNews(arg0);
            return result;
        }
    }
    async deleteSportsCategory(arg0: SportId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSportsCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSportsCategory(arg0);
            return result;
        }
    }
    async getAllAthletes(): Promise<Array<Athlete>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAthletes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAthletes();
            return result;
        }
    }
    async getAllData(): Promise<{
        news: Array<NewsHighlight>;
        athletes: Array<Athlete>;
        events: Array<SportsEvent>;
        sportsCategories: Array<SportsCategory>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllData();
                return from_candid_record_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllData();
            return from_candid_record_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEvents(): Promise<Array<SportsEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNews(): Promise<Array<NewsHighlight>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNews();
            return result;
        }
    }
    async getAllSportsCategories(): Promise<Array<SportsCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSportsCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSportsCategories();
            return result;
        }
    }
    async getEventsByStatus(arg0: Status): Promise<Array<SportsEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByStatus(to_candid_Status_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByStatus(to_candid_Status_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAthlete(arg0: AthleteId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAthlete(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAthlete(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateEvent(arg0: EventId, arg1: string, arg2: string, arg3: Time, arg4: string, arg5: string, arg6: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Status_n1(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Status_n1(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateNews(arg0: NewsId, arg1: string, arg2: string, arg3: string, arg4: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNews(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNews(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateSportsCategory(arg0: SportId, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSportsCategory(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSportsCategory(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_SportsEvent_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SportsEvent): SportsEvent {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    news: Array<_NewsHighlight>;
    athletes: Array<_Athlete>;
    events: Array<_SportsEvent>;
    sportsCategories: Array<_SportsCategory>;
}): {
    news: Array<NewsHighlight>;
    athletes: Array<Athlete>;
    events: Array<SportsEvent>;
    sportsCategories: Array<SportsCategory>;
} {
    return {
        news: value.news,
        athletes: value.athletes,
        events: from_candid_vec_n4(_uploadFile, _downloadFile, value.events),
        sportsCategories: value.sportsCategories
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EventId;
    status: _Status;
    title: string;
    date: _Time;
    description: string;
    sportType: string;
    location: string;
}): {
    id: EventId;
    status: Status;
    title: string;
    date: Time;
    description: string;
    sportType: string;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n7(_uploadFile, _downloadFile, value.status),
        title: value.title,
        date: value.date,
        description: value.description,
        sportType: value.sportType,
        location: value.location
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    live: null;
} | {
    completed: null;
}): Status {
    return "upcoming" in value ? Status.upcoming : "live" in value ? Status.live : "completed" in value ? Status.completed : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SportsEvent>): Array<SportsEvent> {
    return value.map((x)=>from_candid_SportsEvent_n5(_uploadFile, _downloadFile, x));
}
function to_candid_Status_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    upcoming: null;
} | {
    live: null;
} | {
    completed: null;
} {
    return value == Status.upcoming ? {
        upcoming: null
    } : value == Status.live ? {
        live: null
    } : value == Status.completed ? {
        completed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
